### ISSUE TITLE
Add a Footer component

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#1]
- Links for github repo, twitter (https://twitter.com/hacktobered)
- Use React Icons

**Comment by mareeekb1** [comment]
Hello, Can I take this one ?

**Comment by saranshsinhaa** [comment]
I would like to work on this, Please assign me this issue.
Thank you!

**Comment by ankitwww** [comment]
Feel free to reach out in case of any issues

**Comment by ankitwww** [comment]
@WraitH17 still working on it?

**Comment by saranshsinhaa** [comment]
yes! sorry for the delay, I had exams xD

**Comment by ankitwww** [comment]
No worries - take your time. I am unassigning the task for now but when ready - Send a PR.

**Comment by pedroagcf** [comment]
Hey, I can help with that @ankitwww
