### ISSUE TITLE
Remove Share button from the Card

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#11]
So that it won't appear in the downloaded image itself

![image](https://user-images.githubusercontent.com/14895768/194980071-9083e87e-f6c1-4335-8a35-a138d3e92608.png)

**Comment by pedroagcf** [comment]
Hey, I can address that

**Comment by ankitwww** [comment]
Go for it @pedroagcf ... feel free to reach out in case you are stuck

**Comment by pedroagcf** [comment]
you can find my PR [here](https://github.com/hacktobered/hacktobered.com/pull/20) @ankitwww

**Comment by ankitwww** [comment]
More clarifications here - https://github.com/hacktobered/hacktobered.com/pull/20#issuecomment-1275487872
@pedroagcf
