### ISSUE TITLE
Show "how to" content for the users without pull requests

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#16]
If the logged-in user does not have any existing pull requests - Show them some helpful content on how they can participate in Hacktoberfest. Provide the link to the main event website. 
Find useful resources and put links.

**Comment by chashamsarao** [comment]
Hi @ankitwww, I would like to work on this. Please assign this to me.

**Comment by ankitwww** [comment]
I just assigned you #19  and don't want to bombard you with another ticket for now. Let's start this once you are done with that.

**Comment by pedroagcf** [comment]
Hey, I can work on that

**Comment by ankitwww** [comment]
@pedroagcf I just assigned you #3  , lets's come back to this once you are done with the privacy page.

**Comment by pedroagcf** [comment]
sure!

**Comment by pedroagcf** [comment]
hey, Can I address that now? @ankitwww

**Comment by ankitwww** [comment]
Yup, go for it. Also, make sure you have the latest code from main branch - there might be some breaking changes in profile page. any feedback or design changes - I am all up for it!
