### ISSUE TITLE
For users with 4+ PRs - show "challenge completed" sort of card on profile page

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#19]
And users should be able to share it just like other cards

**Comment by chashamsarao** [comment]
Hello @ankitwww... Please assign this to me..

**Comment by ankitwww** [comment]
Here you go @chashamsarao . Please remember this work item is part of our 2210 Week 2 Release. Feel free to reach out in case of doubts/queries

**Comment by chashamsarao** [comment]
okk
Does that mean the deadline is 14 Oct?

**Comment by ankitwww** [comment]
No, 16th Oct end of day - we will start new milestone on 17th Oct

![image](https://user-images.githubusercontent.com/14895768/195272817-c2ef90d2-8e15-4d23-8285-61ef781bc2c8.png)

**Comment by deepaksuthar40128** [comment]
Can you assign it to me

**Comment by ankitwww** [comment]
@deepaksuthar40128  - Sure, give it a try now. Please take a look into apiWrapper.tsx -> fetchUserPullRequests function's output - this might give some insights

**Comment by ankitwww** [comment]
This feature is not required anymore as we are handling this scenario already
