### ISSUE TITLE
[Mobile] option to Sign Out in Nav bar

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#2]
Desktop Nav bar has Sign Out option - however mobile menu does not have that

**Comment by tinuh** [comment]
hey I would love to work on this!

**Comment by ankitwww** [comment]
go ahead @tinuh ... feel free to reach out in case of any issues

**Comment by ankitwww** [comment]
🎉 @tinuh ! Thanks for your contribution. We are live with it!! Don't forget to share your achievement using "our" tool - https://www.hacktobered.com/share/hacktobered/hacktobered.com/pull/18 

![tinuh](https://user-images.githubusercontent.com/14895768/195225483-f87d7dc5-7229-4363-9ff8-b9e7e7310f00.png)
