### ISSUE TITLE
Refactor Types folder

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#21]
Separate every type in a single file, and fix their references across the repo.
types\SearchResults.tsx can be ignored, but PREntry needs to be broken into single file and a better name

**Comment by rodolfonei** [comment]
I would like to work on this one, please

**Comment by ankitwww** [comment]
@rodolfonei go ahead.

**Comment by ankitwww** [comment]
Thanks for your help @rodolfonei
