### ISSUE TITLE
Remove Share button from the CheerCard

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#22]
Take a look at #11  and its PR. We need a similar change for components\PullRequestDetailCards\CheerCard.tsx
We need to remove the share button from the generated image

![image](https://user-images.githubusercontent.com/14895768/195252573-287acf46-96dd-49b5-b7fe-98979c63258e.png)

**Comment by kaustav202** [comment]
can I fix this @ankitwww

**Comment by ankitwww** [comment]
Yup @kaustav202

**Comment by ankitwww** [comment]
this commit should fix it https://github.com/hacktobered/hacktobered.com/commit/bd413c3749f1cbf3a12daf257605dda43ad80aa6
