### ISSUE TITLE
Fix logo at Nav bar

### ISSUE THREAD

**Issue by ankitwww** [hacktobered/hacktobered.com#7]
We don't have logo at nav bar (desktop as well mobile - check once though).
![image](https://user-images.githubusercontent.com/14895768/194972544-ec5e9e6c-9ca7-441f-bc71-e532a034b233.png)

Lots of files are available in public folder. Also, this - https://hacktobered.s3.us-west-2.amazonaws.com/hacktobered.png

**Comment by rsarthak** [comment]
please assign this to me.

**Comment by ankitwww** [comment]
Done! Feel free to reach out if you need any help!

**Comment by ankitwww** [comment]
FIxed by PR https://github.com/hacktobered/hacktobered.com/pull/28 - kudos @rsarthak
